<?php
namespace MarghoobSuleman\HashtagCms\Database\Seeds;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySiteTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $table_name = 'country_site';

        $country_site = array(
            array('country_id' => '1','site_id' => '1'),
            array('country_id' => '2','site_id' => '1'),
            array('country_id' => '3','site_id' => '1'),
            array('country_id' => '4','site_id' => '1'),
            array('country_id' => '5','site_id' => '1'),
            array('country_id' => '6','site_id' => '1'),
            array('country_id' => '7','site_id' => '1'),
            array('country_id' => '8','site_id' => '1'),
            array('country_id' => '9','site_id' => '1'),
            array('country_id' => '10','site_id' => '1'),
            array('country_id' => '11','site_id' => '1'),
            array('country_id' => '12','site_id' => '1'),
            array('country_id' => '13','site_id' => '1'),
            array('country_id' => '14','site_id' => '1'),
            array('country_id' => '15','site_id' => '1'),
            array('country_id' => '16','site_id' => '1'),
            array('country_id' => '17','site_id' => '1'),
            array('country_id' => '18','site_id' => '1'),
            array('country_id' => '19','site_id' => '1'),
            array('country_id' => '20','site_id' => '1'),
            array('country_id' => '21','site_id' => '1'),
            array('country_id' => '22','site_id' => '1'),
            array('country_id' => '23','site_id' => '1'),
            array('country_id' => '24','site_id' => '1'),
            array('country_id' => '25','site_id' => '1'),
            array('country_id' => '26','site_id' => '1'),
            array('country_id' => '27','site_id' => '1'),
            array('country_id' => '28','site_id' => '1'),
            array('country_id' => '29','site_id' => '1'),
            array('country_id' => '30','site_id' => '1'),
            array('country_id' => '31','site_id' => '1'),
            array('country_id' => '32','site_id' => '1'),
            array('country_id' => '33','site_id' => '1'),
            array('country_id' => '34','site_id' => '1'),
            array('country_id' => '35','site_id' => '1'),
            array('country_id' => '36','site_id' => '1'),
            array('country_id' => '37','site_id' => '1'),
            array('country_id' => '38','site_id' => '1'),
            array('country_id' => '39','site_id' => '1'),
            array('country_id' => '40','site_id' => '1'),
            array('country_id' => '41','site_id' => '1'),
            array('country_id' => '42','site_id' => '1'),
            array('country_id' => '43','site_id' => '1'),
            array('country_id' => '44','site_id' => '1'),
            array('country_id' => '45','site_id' => '1'),
            array('country_id' => '46','site_id' => '1'),
            array('country_id' => '47','site_id' => '1'),
            array('country_id' => '48','site_id' => '1'),
            array('country_id' => '49','site_id' => '1'),
            array('country_id' => '50','site_id' => '1'),
            array('country_id' => '51','site_id' => '1'),
            array('country_id' => '52','site_id' => '1'),
            array('country_id' => '53','site_id' => '1'),
            array('country_id' => '54','site_id' => '1'),
            array('country_id' => '55','site_id' => '1'),
            array('country_id' => '56','site_id' => '1'),
            array('country_id' => '57','site_id' => '1'),
            array('country_id' => '58','site_id' => '1'),
            array('country_id' => '59','site_id' => '1'),
            array('country_id' => '60','site_id' => '1'),
            array('country_id' => '61','site_id' => '1'),
            array('country_id' => '62','site_id' => '1'),
            array('country_id' => '63','site_id' => '1'),
            array('country_id' => '64','site_id' => '1'),
            array('country_id' => '65','site_id' => '1'),
            array('country_id' => '66','site_id' => '1'),
            array('country_id' => '67','site_id' => '1'),
            array('country_id' => '68','site_id' => '1'),
            array('country_id' => '69','site_id' => '1'),
            array('country_id' => '70','site_id' => '1'),
            array('country_id' => '71','site_id' => '1'),
            array('country_id' => '72','site_id' => '1'),
            array('country_id' => '73','site_id' => '1'),
            array('country_id' => '74','site_id' => '1'),
            array('country_id' => '75','site_id' => '1'),
            array('country_id' => '76','site_id' => '1'),
            array('country_id' => '77','site_id' => '1'),
            array('country_id' => '78','site_id' => '1'),
            array('country_id' => '79','site_id' => '1'),
            array('country_id' => '80','site_id' => '1'),
            array('country_id' => '81','site_id' => '1'),
            array('country_id' => '82','site_id' => '1'),
            array('country_id' => '83','site_id' => '1'),
            array('country_id' => '84','site_id' => '1'),
            array('country_id' => '85','site_id' => '1'),
            array('country_id' => '86','site_id' => '1'),
            array('country_id' => '87','site_id' => '1'),
            array('country_id' => '88','site_id' => '1'),
            array('country_id' => '89','site_id' => '1'),
            array('country_id' => '90','site_id' => '1'),
            array('country_id' => '91','site_id' => '1'),
            array('country_id' => '92','site_id' => '1'),
            array('country_id' => '93','site_id' => '1'),
            array('country_id' => '94','site_id' => '1'),
            array('country_id' => '95','site_id' => '1'),
            array('country_id' => '96','site_id' => '1'),
            array('country_id' => '97','site_id' => '1'),
            array('country_id' => '98','site_id' => '1'),
            array('country_id' => '99','site_id' => '1'),
            array('country_id' => '100','site_id' => '1'),
            array('country_id' => '101','site_id' => '1'),
            array('country_id' => '102','site_id' => '1'),
            array('country_id' => '103','site_id' => '1'),
            array('country_id' => '104','site_id' => '1'),
            array('country_id' => '105','site_id' => '1'),
            array('country_id' => '106','site_id' => '1'),
            array('country_id' => '107','site_id' => '1'),
            array('country_id' => '108','site_id' => '1'),
            array('country_id' => '109','site_id' => '1'),
            array('country_id' => '110','site_id' => '1'),
            array('country_id' => '111','site_id' => '1'),
            array('country_id' => '112','site_id' => '1'),
            array('country_id' => '113','site_id' => '1'),
            array('country_id' => '114','site_id' => '1'),
            array('country_id' => '115','site_id' => '1'),
            array('country_id' => '116','site_id' => '1'),
            array('country_id' => '117','site_id' => '1'),
            array('country_id' => '118','site_id' => '1'),
            array('country_id' => '119','site_id' => '1'),
            array('country_id' => '120','site_id' => '1'),
            array('country_id' => '121','site_id' => '1'),
            array('country_id' => '122','site_id' => '1'),
            array('country_id' => '123','site_id' => '1'),
            array('country_id' => '124','site_id' => '1'),
            array('country_id' => '125','site_id' => '1'),
            array('country_id' => '126','site_id' => '1'),
            array('country_id' => '127','site_id' => '1'),
            array('country_id' => '128','site_id' => '1'),
            array('country_id' => '129','site_id' => '1'),
            array('country_id' => '130','site_id' => '1'),
            array('country_id' => '131','site_id' => '1'),
            array('country_id' => '132','site_id' => '1'),
            array('country_id' => '133','site_id' => '1'),
            array('country_id' => '134','site_id' => '1'),
            array('country_id' => '135','site_id' => '1'),
            array('country_id' => '136','site_id' => '1'),
            array('country_id' => '137','site_id' => '1'),
            array('country_id' => '138','site_id' => '1'),
            array('country_id' => '139','site_id' => '1'),
            array('country_id' => '140','site_id' => '1'),
            array('country_id' => '141','site_id' => '1'),
            array('country_id' => '142','site_id' => '1'),
            array('country_id' => '143','site_id' => '1'),
            array('country_id' => '144','site_id' => '1'),
            array('country_id' => '145','site_id' => '1'),
            array('country_id' => '146','site_id' => '1'),
            array('country_id' => '147','site_id' => '1'),
            array('country_id' => '148','site_id' => '1'),
            array('country_id' => '149','site_id' => '1'),
            array('country_id' => '150','site_id' => '1'),
            array('country_id' => '151','site_id' => '1'),
            array('country_id' => '152','site_id' => '1'),
            array('country_id' => '153','site_id' => '1'),
            array('country_id' => '154','site_id' => '1'),
            array('country_id' => '155','site_id' => '1'),
            array('country_id' => '156','site_id' => '1'),
            array('country_id' => '157','site_id' => '1'),
            array('country_id' => '158','site_id' => '1'),
            array('country_id' => '159','site_id' => '1'),
            array('country_id' => '160','site_id' => '1'),
            array('country_id' => '161','site_id' => '1'),
            array('country_id' => '162','site_id' => '1'),
            array('country_id' => '163','site_id' => '1'),
            array('country_id' => '164','site_id' => '1'),
            array('country_id' => '165','site_id' => '1'),
            array('country_id' => '166','site_id' => '1'),
            array('country_id' => '167','site_id' => '1'),
            array('country_id' => '168','site_id' => '1'),
            array('country_id' => '169','site_id' => '1'),
            array('country_id' => '170','site_id' => '1'),
            array('country_id' => '171','site_id' => '1'),
            array('country_id' => '172','site_id' => '1'),
            array('country_id' => '173','site_id' => '1'),
            array('country_id' => '174','site_id' => '1'),
            array('country_id' => '175','site_id' => '1'),
            array('country_id' => '176','site_id' => '1'),
            array('country_id' => '177','site_id' => '1'),
            array('country_id' => '178','site_id' => '1'),
            array('country_id' => '179','site_id' => '1'),
            array('country_id' => '180','site_id' => '1'),
            array('country_id' => '181','site_id' => '1'),
            array('country_id' => '182','site_id' => '1'),
            array('country_id' => '183','site_id' => '1'),
            array('country_id' => '184','site_id' => '1'),
            array('country_id' => '185','site_id' => '1'),
            array('country_id' => '186','site_id' => '1'),
            array('country_id' => '187','site_id' => '1'),
            array('country_id' => '188','site_id' => '1'),
            array('country_id' => '189','site_id' => '1'),
            array('country_id' => '190','site_id' => '1'),
            array('country_id' => '191','site_id' => '1'),
            array('country_id' => '192','site_id' => '1'),
            array('country_id' => '193','site_id' => '1'),
            array('country_id' => '194','site_id' => '1'),
            array('country_id' => '195','site_id' => '1'),
            array('country_id' => '196','site_id' => '1'),
            array('country_id' => '197','site_id' => '1'),
            array('country_id' => '198','site_id' => '1'),
            array('country_id' => '199','site_id' => '1'),
            array('country_id' => '200','site_id' => '1'),
            array('country_id' => '201','site_id' => '1'),
            array('country_id' => '202','site_id' => '1'),
            array('country_id' => '203','site_id' => '1'),
            array('country_id' => '204','site_id' => '1'),
            array('country_id' => '205','site_id' => '1'),
            array('country_id' => '206','site_id' => '1'),
            array('country_id' => '207','site_id' => '1'),
            array('country_id' => '208','site_id' => '1'),
            array('country_id' => '209','site_id' => '1'),
            array('country_id' => '210','site_id' => '1'),
            array('country_id' => '211','site_id' => '1'),
            array('country_id' => '212','site_id' => '1'),
            array('country_id' => '213','site_id' => '1'),
            array('country_id' => '214','site_id' => '1'),
            array('country_id' => '215','site_id' => '1'),
            array('country_id' => '216','site_id' => '1'),
            array('country_id' => '217','site_id' => '1'),
            array('country_id' => '218','site_id' => '1'),
            array('country_id' => '219','site_id' => '1'),
            array('country_id' => '220','site_id' => '1'),
            array('country_id' => '221','site_id' => '1'),
            array('country_id' => '222','site_id' => '1'),
            array('country_id' => '223','site_id' => '1'),
            array('country_id' => '224','site_id' => '1'),
            array('country_id' => '225','site_id' => '1'),
            array('country_id' => '226','site_id' => '1'),
            array('country_id' => '227','site_id' => '1'),
            array('country_id' => '228','site_id' => '1'),
            array('country_id' => '229','site_id' => '1'),
            array('country_id' => '230','site_id' => '1'),
            array('country_id' => '231','site_id' => '1'),
            array('country_id' => '232','site_id' => '1'),
            array('country_id' => '233','site_id' => '1'),
            array('country_id' => '234','site_id' => '1'),
            array('country_id' => '235','site_id' => '1'),
            array('country_id' => '236','site_id' => '1'),
            array('country_id' => '237','site_id' => '1'),
            array('country_id' => '238','site_id' => '1'),
            array('country_id' => '239','site_id' => '1'),
            array('country_id' => '240','site_id' => '1'),
            array('country_id' => '241','site_id' => '1'),
            array('country_id' => '242','site_id' => '1'),
            array('country_id' => '243','site_id' => '1'),
            array('country_id' => '244','site_id' => '1')
        );


        if(DB::table($table_name)->get()->count() == 0) {
            DB::table($table_name)->insert($country_site);
        } else {
            echo "SeedingError: `$table_name` table is not empty\n";
        }
    }
}
