<?php
namespace MarghoobSuleman\HashtagCms\Database\Seeds;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class IssuesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $table_name = 'issues';
        $table_name_langs = 'issue_langs';

        $issues = array(
            array('id' => '1','issue_type_id' => '1','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '2','issue_type_id' => '1','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '3','issue_type_id' => '1','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '4','issue_type_id' => '1','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '5','issue_type_id' => '1','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '6','issue_type_id' => '1','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => '2020-04-25 06:31:42','deleted_at' => NULL),
            array('id' => '7','issue_type_id' => '1','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '8','issue_type_id' => '1','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '9','issue_type_id' => '1','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '10','issue_type_id' => '1','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '11','issue_type_id' => '1','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '12','issue_type_id' => '1','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '13','issue_type_id' => '1','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '14','issue_type_id' => '1','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '15','issue_type_id' => '1','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '16','issue_type_id' => '1','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '17','issue_type_id' => '1','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '18','issue_type_id' => '1','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '19','issue_type_id' => '1','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '20','issue_type_id' => '1','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '21','issue_type_id' => '1','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '22','issue_type_id' => '1','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '23','issue_type_id' => '1','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '24','issue_type_id' => '1','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '25','issue_type_id' => '1','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '26','issue_type_id' => '2','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '27','issue_type_id' => '2','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '28','issue_type_id' => '2','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '29','issue_type_id' => '2','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '30','issue_type_id' => '2','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '31','issue_type_id' => '3','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '32','issue_type_id' => '4','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '33','issue_type_id' => '4','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '34','issue_type_id' => '4','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '35','issue_type_id' => '4','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '36','issue_type_id' => '4','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '37','issue_type_id' => '4','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '38','issue_type_id' => '4','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '39','issue_type_id' => '5','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '40','issue_type_id' => '5','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '41','issue_type_id' => '5','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '42','issue_type_id' => '5','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '43','issue_type_id' => '6','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '44','issue_type_id' => '6','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '45','issue_type_id' => '7','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '46','issue_type_id' => '7','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '47','issue_type_id' => '7','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '48','issue_type_id' => '7','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '49','issue_type_id' => '7','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '50','issue_type_id' => '7','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '51','issue_type_id' => '7','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '52','issue_type_id' => '7','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '53','issue_type_id' => '7','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '54','issue_type_id' => '8','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '55','issue_type_id' => '8','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '56','issue_type_id' => '8','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '57','issue_type_id' => '9','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '58','issue_type_id' => '9','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '59','issue_type_id' => '9','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '60','issue_type_id' => '9','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '61','issue_type_id' => '9','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '62','issue_type_id' => '9','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '63','issue_type_id' => '9','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '64','issue_type_id' => '9','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '65','issue_type_id' => '9','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '66','issue_type_id' => '9','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '67','issue_type_id' => '9','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '68','issue_type_id' => '9','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '69','issue_type_id' => '9','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '70','issue_type_id' => '10','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '71','issue_type_id' => '10','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '72','issue_type_id' => '10','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '73','issue_type_id' => '10','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '74','issue_type_id' => '10','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '75','issue_type_id' => '10','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '76','issue_type_id' => '10','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '77','issue_type_id' => '10','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '78','issue_type_id' => '10','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '79','issue_type_id' => '10','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '80','issue_type_id' => '10','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '81','issue_type_id' => '10','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '82','issue_type_id' => '10','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '83','issue_type_id' => '10','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '84','issue_type_id' => '10','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '85','issue_type_id' => '10','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '86','issue_type_id' => '10','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '87','issue_type_id' => '10','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '88','issue_type_id' => '10','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '89','issue_type_id' => '10','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '90','issue_type_id' => '10','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '91','issue_type_id' => '10','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '92','issue_type_id' => '10','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '93','issue_type_id' => '10','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '94','issue_type_id' => '10','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '95','issue_type_id' => '10','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '96','issue_type_id' => '10','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '97','issue_type_id' => '10','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '98','issue_type_id' => '10','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '99','issue_type_id' => '10','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '100','issue_type_id' => '10','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '101','issue_type_id' => '10','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '102','issue_type_id' => '11','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '103','issue_type_id' => '11','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '104','issue_type_id' => '11','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '105','issue_type_id' => '11','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '106','issue_type_id' => '11','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '107','issue_type_id' => '11','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '108','issue_type_id' => '12','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '109','issue_type_id' => '12','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '110','issue_type_id' => '12','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '111','issue_type_id' => '13','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '112','issue_type_id' => '13','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '113','issue_type_id' => '13','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '114','issue_type_id' => '13','site_id' => '1','publish_status' => '1','position' => NULL,'created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL)
        );

        $issue_langs = array(
            array('issue_id' => '1','lang_id' => '1','name' => 'Swachh Bharat-&gt;Garbage Dumps','created_at' => '2020-04-24 18:42:30','updated_at' => '2020-04-24 18:42:30','deleted_at' => NULL),
            array('issue_id' => '2','lang_id' => '1','name' => 'Sweeping','created_at' => '2020-04-24 18:42:50','updated_at' => '2020-04-24 18:42:50','deleted_at' => NULL),
            array('issue_id' => '3','lang_id' => '1','name' => 'Burning Garbage','created_at' => '2020-04-24 18:43:06','updated_at' => '2020-04-24 18:43:06','deleted_at' => NULL),
            array('issue_id' => '4','lang_id' => '1','name' => 'Malba Stuck','created_at' => '2020-04-24 18:47:29','updated_at' => '2020-04-24 18:47:29','deleted_at' => NULL),
            array('issue_id' => '5','lang_id' => '1','name' => 'Potholes','created_at' => '2020-04-25 06:31:07','updated_at' => '2020-04-25 06:31:07','deleted_at' => NULL),
            array('issue_id' => '6','lang_id' => '1','name' => 'Swachh Bharat -> Urination in Public / Defection','created_at' => '2020-04-25 06:31:27','updated_at' => '2020-04-25 06:31:42','deleted_at' => NULL),
            array('issue_id' => '7','lang_id' => '1','name' => 'Stray Dogs','created_at' => '2020-04-25 06:31:58','updated_at' => '2020-04-25 06:31:58','deleted_at' => NULL),
            array('issue_id' => '8','lang_id' => '1','name' => 'Swachh Bharat -> No electricity in public toilets','created_at' => '2020-04-25 06:32:18','updated_at' => '2020-04-25 06:32:18','deleted_at' => NULL),
            array('issue_id' => '9','lang_id' => '1','name' => 'Swachh Bharat -> Sweeping not done','created_at' => '2020-04-25 06:34:19','updated_at' => '2020-04-25 06:34:19','deleted_at' => NULL),
            array('issue_id' => '10','lang_id' => '1','name' => 'Swachh Bharat -> No water supply in public toilets','created_at' => '2020-04-25 06:34:31','updated_at' => '2020-04-25 06:34:31','deleted_at' => NULL),
            array('issue_id' => '11','lang_id' => '1','name' => 'Swachh Bharat -> Public Toilets Blockage','created_at' => '2020-04-25 06:34:46','updated_at' => '2020-04-25 06:34:46','deleted_at' => NULL),
            array('issue_id' => '12','lang_id' => '1','name' => 'Swachh Bharat -> Garbage Vehicle not arrived','created_at' => '2020-04-25 06:34:57','updated_at' => '2020-04-25 06:34:57','deleted_at' => NULL),
            array('issue_id' => '13','lang_id' => '1','name' => 'Swachh Bharat -> Dead Animal','created_at' => '2020-04-25 06:35:08','updated_at' => '2020-04-25 06:35:08','deleted_at' => NULL),
            array('issue_id' => '14','lang_id' => '1','name' => 'Swachh Bharat -> Dustbin Not Cleaned','created_at' => '2020-04-25 06:35:17','updated_at' => '2020-04-25 06:35:17','deleted_at' => NULL),
            array('issue_id' => '15','lang_id' => '1','name' => 'Swachh Bharat -> Public toilet(s) cleaning','created_at' => '2020-04-25 06:35:30','updated_at' => '2020-04-25 06:35:30','deleted_at' => NULL),
            array('issue_id' => '16','lang_id' => '1','name' => 'Swachh Bharat -> Open Manholes Or Drains','created_at' => '2020-04-25 06:35:49','updated_at' => '2020-04-25 06:35:49','deleted_at' => NULL),
            array('issue_id' => '17','lang_id' => '1','name' => 'Swachh Bharat -> Sewerage or Storm Water Overflow','created_at' => '2020-04-25 06:36:02','updated_at' => '2020-04-25 06:36:02','deleted_at' => NULL),
            array('issue_id' => '18','lang_id' => '1','name' => 'Swachh Bharat -> Stagnant Water On The Road','created_at' => '2020-04-25 06:36:14','updated_at' => '2020-04-25 06:36:14','deleted_at' => NULL),
            array('issue_id' => '19','lang_id' => '1','name' => 'Swachh Bharat -> Improper Disposal of Fecal Waste/Septage','created_at' => '2020-04-25 06:36:25','updated_at' => '2020-04-25 06:36:25','deleted_at' => NULL),
            array('issue_id' => '20','lang_id' => '1','name' => 'Debris Removal/Construction Material','created_at' => '2020-04-25 06:36:56','updated_at' => '2020-04-25 06:36:56','deleted_at' => NULL),
            array('issue_id' => '21','lang_id' => '1','name' => 'Burning Of Garbage In Open Space','created_at' => '2020-04-25 06:37:08','updated_at' => '2020-04-25 06:37:08','deleted_at' => NULL),
            array('issue_id' => '22','lang_id' => '1','name' => 'Malaria Fogging/Spray','created_at' => '2020-04-25 06:37:19','updated_at' => '2020-04-25 06:37:19','deleted_at' => NULL),
            array('issue_id' => '23','lang_id' => '1','name' => 'Monkey Menace','created_at' => '2020-04-25 06:37:32','updated_at' => '2020-04-25 06:37:32','deleted_at' => NULL),
            array('issue_id' => '24','lang_id' => '1','name' => 'Health Challan Issue','created_at' => '2020-04-25 06:37:45','updated_at' => '2020-04-25 06:37:45','deleted_at' => NULL),
            array('issue_id' => '25','lang_id' => '1','name' => 'Horticulture Waste','created_at' => '2020-04-25 06:37:58','updated_at' => '2020-04-25 06:37:58','deleted_at' => NULL),
            array('issue_id' => '26','lang_id' => '1','name' => 'Unauthorised Parking','created_at' => '2020-04-25 06:38:11','updated_at' => '2020-04-25 06:38:11','deleted_at' => NULL),
            array('issue_id' => '27','lang_id' => '1','name' => 'Unauthorised Posters, Banner etc.','created_at' => '2020-04-25 06:38:22','updated_at' => '2020-04-25 06:38:22','deleted_at' => NULL),
            array('issue_id' => '28','lang_id' => '1','name' => 'Unauthorised Hawkers','created_at' => '2020-04-25 06:38:33','updated_at' => '2020-04-25 06:38:33','deleted_at' => NULL),
            array('issue_id' => '29','lang_id' => '1','name' => 'Encroachment','created_at' => '2020-04-25 06:38:42','updated_at' => '2020-04-25 06:38:42','deleted_at' => NULL),
            array('issue_id' => '30','lang_id' => '1','name' => 'Unauthorised Advertisement(Hoardings,posters etc.)','created_at' => '2020-04-25 06:38:57','updated_at' => '2020-04-25 06:38:57','deleted_at' => NULL),
            array('issue_id' => '31','lang_id' => '1','name' => 'Fire','created_at' => '2020-04-25 06:39:08','updated_at' => '2020-04-25 06:39:08','deleted_at' => NULL),
            array('issue_id' => '32','lang_id' => '1','name' => 'Toilet Blockage','created_at' => '2020-04-25 06:39:21','updated_at' => '2020-04-25 06:39:21','deleted_at' => NULL),
            array('issue_id' => '33','lang_id' => '1','name' => 'No Electricity','created_at' => '2020-04-25 06:39:31','updated_at' => '2020-04-25 06:39:31','deleted_at' => NULL),
            array('issue_id' => '34','lang_id' => '1','name' => 'No Water Supply','created_at' => '2020-04-25 06:39:42','updated_at' => '2020-04-25 06:39:42','deleted_at' => NULL),
            array('issue_id' => '35','lang_id' => '1','name' => 'Toilet Cleaning','created_at' => '2020-04-25 06:39:56','updated_at' => '2020-04-25 06:39:56','deleted_at' => NULL),
            array('issue_id' => '36','lang_id' => '1','name' => 'Maintenance Of PTU','created_at' => '2020-04-25 06:40:08','updated_at' => '2020-04-25 06:40:08','deleted_at' => NULL),
            array('issue_id' => '37','lang_id' => '1','name' => 'Operator Ask for Money','created_at' => '2020-04-25 06:40:18','updated_at' => '2020-04-25 06:40:18','deleted_at' => NULL),
            array('issue_id' => '38','lang_id' => '1','name' => 'Inspection Public Toilets','created_at' => '2020-04-25 06:40:28','updated_at' => '2020-04-25 06:40:28','deleted_at' => NULL),
            array('issue_id' => '39','lang_id' => '1','name' => 'Maintenance of Parks / Round About','created_at' => '2020-04-25 06:40:45','updated_at' => '2020-04-25 06:40:45','deleted_at' => NULL),
            array('issue_id' => '40','lang_id' => '1','name' => 'Tree Fall','created_at' => '2020-04-25 06:41:01','updated_at' => '2020-04-25 06:41:01','deleted_at' => NULL),
            array('issue_id' => '41','lang_id' => '1','name' => 'Pruning of Trees','created_at' => '2020-04-25 06:41:13','updated_at' => '2020-04-25 06:41:13','deleted_at' => NULL),
            array('issue_id' => '42','lang_id' => '1','name' => 'Removal Of Horticulture Waste','created_at' => '2020-04-25 06:41:23','updated_at' => '2020-04-25 06:41:23','deleted_at' => NULL),
            array('issue_id' => '43','lang_id' => '1','name' => 'Indoor gym Maintenance','created_at' => '2020-04-25 06:41:41','updated_at' => '2020-04-25 06:41:41','deleted_at' => NULL),
            array('issue_id' => '44','lang_id' => '1','name' => 'Open Gym Maintenance','created_at' => '2020-04-25 06:41:54','updated_at' => '2020-04-25 06:41:54','deleted_at' => NULL),
            array('issue_id' => '45','lang_id' => '1','name' => 'AC not working','created_at' => '2020-04-25 06:42:06','updated_at' => '2020-04-25 06:42:06','deleted_at' => NULL),
            array('issue_id' => '46','lang_id' => '1','name' => 'Street Light not working','created_at' => '2020-04-25 06:42:16','updated_at' => '2020-04-25 06:42:16','deleted_at' => NULL),
            array('issue_id' => '47','lang_id' => '1','name' => 'Electric-BM -> Water Cooler not working','created_at' => '2020-04-25 06:42:27','updated_at' => '2020-04-25 06:42:27','deleted_at' => NULL),
            array('issue_id' => '48','lang_id' => '1','name' => 'Electric-BM -> CCTV not working','created_at' => '2020-04-25 06:42:38','updated_at' => '2020-04-25 06:42:38','deleted_at' => NULL),
            array('issue_id' => '49','lang_id' => '1','name' => 'Fire In Pole','created_at' => '2020-04-25 06:42:48','updated_at' => '2020-04-25 06:42:48','deleted_at' => NULL),
            array('issue_id' => '50','lang_id' => '1','name' => 'Electric-BM -> Appliances Burnt','created_at' => '2020-04-25 06:43:02','updated_at' => '2020-04-25 06:43:02','deleted_at' => NULL),
            array('issue_id' => '51','lang_id' => '1','name' => 'Wire Hanging/Broken','created_at' => '2020-04-25 06:43:12','updated_at' => '2020-04-25 06:43:12','deleted_at' => NULL),
            array('issue_id' => '52','lang_id' => '1','name' => 'High mask light not working','created_at' => '2020-04-25 06:43:53','updated_at' => '2020-04-25 06:43:53','deleted_at' => NULL),
            array('issue_id' => '53','lang_id' => '1','name' => 'Electric-BM -> Electric Building Maintenance','created_at' => '2020-04-25 06:44:05','updated_at' => '2020-04-25 06:44:05','deleted_at' => NULL),
            array('issue_id' => '54','lang_id' => '1','name' => 'No Current / Supply','created_at' => '2020-04-25 06:44:16','updated_at' => '2020-04-25 06:44:29','deleted_at' => NULL),
            array('issue_id' => '55','lang_id' => '1','name' => 'Voltage Fluctuation','created_at' => '2020-04-25 06:44:42','updated_at' => '2020-04-25 06:44:42','deleted_at' => NULL),
            array('issue_id' => '56','lang_id' => '1','name' => 'Panel Box Not Working','created_at' => '2020-04-25 06:44:53','updated_at' => '2020-04-25 06:44:53','deleted_at' => NULL),
            array('issue_id' => '57','lang_id' => '1','name' => 'Meter Fault','created_at' => '2020-04-25 06:45:08','updated_at' => '2020-04-25 06:45:08','deleted_at' => NULL),
            array('issue_id' => '58','lang_id' => '1','name' => 'Meter Reading','created_at' => '2020-04-25 06:45:23','updated_at' => '2020-04-25 06:45:23','deleted_at' => NULL),
            array('issue_id' => '59','lang_id' => '1','name' => 'New Connection','created_at' => '2020-04-25 06:45:37','updated_at' => '2020-04-25 06:45:37','deleted_at' => NULL),
            array('issue_id' => '60','lang_id' => '1','name' => 'Transfer of money and billing','created_at' => '2020-04-25 06:46:09','updated_at' => '2020-04-25 06:46:09','deleted_at' => NULL),
            array('issue_id' => '61','lang_id' => '1','name' => 'Bill related problem','created_at' => '2020-04-25 06:46:19','updated_at' => '2020-04-25 06:46:19','deleted_at' => NULL),
            array('issue_id' => '62','lang_id' => '1','name' => 'Generation Of Electricity Bill','created_at' => '2020-04-25 06:46:33','updated_at' => '2020-04-25 06:46:33','deleted_at' => NULL),
            array('issue_id' => '63','lang_id' => '1','name' => 'Detection of power theft','created_at' => '2020-04-25 06:46:43','updated_at' => '2020-04-25 06:46:43','deleted_at' => NULL),
            array('issue_id' => '64','lang_id' => '1','name' => 'Release of Electricity/Water','created_at' => '2020-04-25 06:46:53','updated_at' => '2020-04-25 06:46:53','deleted_at' => NULL),
            array('issue_id' => '65','lang_id' => '1','name' => 'Smart Meter -> Meter Sparking','created_at' => '2020-04-25 06:47:03','updated_at' => '2020-04-25 06:47:03','deleted_at' => NULL),
            array('issue_id' => '66','lang_id' => '1','name' => 'Smart Meter -> Data not available on consumer portal-mobile app','created_at' => '2020-04-25 06:47:14','updated_at' => '2020-04-25 06:47:14','deleted_at' => NULL),
            array('issue_id' => '67','lang_id' => '1','name' => 'Smart Meter -> Consumer No. not found in mobile app','created_at' => '2020-04-25 06:47:26','updated_at' => '2020-04-25 06:47:26','deleted_at' => NULL),
            array('issue_id' => '68','lang_id' => '1','name' => 'Smart Meter -> Meter details are incorrect in system','created_at' => '2020-04-25 06:47:36','updated_at' => '2020-04-25 06:47:36','deleted_at' => NULL),
            array('issue_id' => '69','lang_id' => '1','name' => 'Smart Meter -> Smart Meter Not Installed','created_at' => '2020-04-25 06:47:48','updated_at' => '2020-04-25 06:47:48','deleted_at' => NULL),
            array('issue_id' => '70','lang_id' => '1','name' => 'Road Drainage -> Drainage Silt','created_at' => '2020-04-25 06:49:49','updated_at' => '2020-04-25 06:49:49','deleted_at' => NULL),
            array('issue_id' => '71','lang_id' => '1','name' => 'Road Drainage -> Drainage Coverage Missing','created_at' => '2020-04-25 06:50:09','updated_at' => '2020-04-25 06:50:09','deleted_at' => NULL),
            array('issue_id' => '72','lang_id' => '1','name' => 'Road Drainage -> Drainage Blocked','created_at' => '2020-04-25 06:50:20','updated_at' => '2020-04-25 06:50:20','deleted_at' => NULL),
            array('issue_id' => '73','lang_id' => '1','name' => 'Road Maintenance -> Bollards Broken','created_at' => '2020-04-25 06:50:29','updated_at' => '2020-04-25 06:50:29','deleted_at' => NULL),
            array('issue_id' => '74','lang_id' => '1','name' => 'Road Maintenance -> Mainhole Cover Missing / Broken','created_at' => '2020-04-25 06:50:42','updated_at' => '2020-04-25 06:50:42','deleted_at' => NULL),
            array('issue_id' => '75','lang_id' => '1','name' => 'Road Maintenance -> Road Signages need repair','created_at' => '2020-04-25 06:50:53','updated_at' => '2020-04-25 06:50:53','deleted_at' => NULL),
            array('issue_id' => '76','lang_id' => '1','name' => 'Road Maintenance -> Potholes','created_at' => '2020-04-25 06:51:04','updated_at' => '2020-04-25 06:51:04','deleted_at' => NULL),
            array('issue_id' => '77','lang_id' => '1','name' => 'Road Maintenance -> Water logging','created_at' => '2020-04-25 06:51:15','updated_at' => '2020-04-25 06:51:15','deleted_at' => NULL),
            array('issue_id' => '78','lang_id' => '1','name' => 'Road Maintenance -> Footpath Broken','created_at' => '2020-04-25 06:51:25','updated_at' => '2020-04-25 06:51:25','deleted_at' => NULL),
            array('issue_id' => '79','lang_id' => '1','name' => 'Road Maintenance -> Maintenance of Foot Over Bridge','created_at' => '2020-04-25 06:51:35','updated_at' => '2020-04-25 06:51:35','deleted_at' => NULL),
            array('issue_id' => '80','lang_id' => '1','name' => 'Road Maintenance -> Open Gym Maintenance','created_at' => '2020-04-25 06:51:46','updated_at' => '2020-04-25 06:51:46','deleted_at' => NULL),
            array('issue_id' => '81','lang_id' => '1','name' => 'Road Maintenance -> Zebra Crossing','created_at' => '2020-04-25 06:51:56','updated_at' => '2020-04-25 06:51:56','deleted_at' => NULL),
            array('issue_id' => '82','lang_id' => '1','name' => 'Road Maintenance -> Drainage Overflow','created_at' => '2020-04-25 06:52:06','updated_at' => '2020-04-25 06:52:06','deleted_at' => NULL),
            array('issue_id' => '83','lang_id' => '1','name' => 'Road Maintenance -> Malba Stacking','created_at' => '2020-04-25 06:52:21','updated_at' => '2020-04-25 06:52:21','deleted_at' => NULL),
            array('issue_id' => '84','lang_id' => '1','name' => 'Road Maintenance -> Spot Fixing','created_at' => '2020-04-25 06:52:51','updated_at' => '2020-04-25 06:52:51','deleted_at' => NULL),
            array('issue_id' => '85','lang_id' => '1','name' => 'Road Maintenance -> Dustbin Not Clean','created_at' => '2020-04-25 06:53:03','updated_at' => '2020-04-25 06:53:03','deleted_at' => NULL),
            array('issue_id' => '86','lang_id' => '1','name' => 'Sewer Maintenance -> Sewer Block','created_at' => '2020-04-25 06:55:23','updated_at' => '2020-04-25 06:55:23','deleted_at' => NULL),
            array('issue_id' => '87','lang_id' => '1','name' => 'Sewer Maintenance -> Sewer Silt / Malba','created_at' => '2020-04-25 06:55:50','updated_at' => '2020-04-25 06:55:50','deleted_at' => NULL),
            array('issue_id' => '88','lang_id' => '1','name' => 'Sewer Maintenance -> Sewer Overflow','created_at' => '2020-04-25 06:56:02','updated_at' => '2020-04-25 06:56:02','deleted_at' => NULL),
            array('issue_id' => '89','lang_id' => '1','name' => 'Sewer Maintenance -> Sewer mainhole cover related','created_at' => '2020-04-25 06:56:14','updated_at' => '2020-04-25 06:56:14','deleted_at' => NULL),
            array('issue_id' => '90','lang_id' => '1','name' => 'Water Maintenance -> Hand Pump','created_at' => '2020-04-25 06:56:24','updated_at' => '2020-04-25 06:56:24','deleted_at' => NULL),
            array('issue_id' => '91','lang_id' => '1','name' => 'Water Maintenance -> Water Tanker Required','created_at' => '2020-04-25 06:56:37','updated_at' => '2020-04-25 06:56:37','deleted_at' => NULL),
            array('issue_id' => '92','lang_id' => '1','name' => 'Water Maintenance -> Meter Faulty','created_at' => '2020-04-25 06:57:27','updated_at' => '2020-04-25 06:57:27','deleted_at' => NULL),
            array('issue_id' => '93','lang_id' => '1','name' => 'Water Maintenance -> Broken Pipeline','created_at' => '2020-04-25 06:57:37','updated_at' => '2020-04-25 06:57:37','deleted_at' => NULL),
            array('issue_id' => '94','lang_id' => '1','name' => 'Water Maintenance -> Contaminated Water','created_at' => '2020-04-25 06:57:47','updated_at' => '2020-04-25 06:57:47','deleted_at' => NULL),
            array('issue_id' => '95','lang_id' => '1','name' => 'Water Maintenance -> Illegal Connection','created_at' => '2020-04-25 06:57:58','updated_at' => '2020-04-25 06:57:58','deleted_at' => NULL),
            array('issue_id' => '96','lang_id' => '1','name' => 'Water Maintenance -> Leakage of Water','created_at' => '2020-04-25 06:58:07','updated_at' => '2020-04-25 06:58:07','deleted_at' => NULL),
            array('issue_id' => '97','lang_id' => '1','name' => 'Water Maintenance -> Low Water  Supply/ No Water','created_at' => '2020-04-25 06:58:18','updated_at' => '2020-04-25 06:58:18','deleted_at' => NULL),
            array('issue_id' => '98','lang_id' => '1','name' => 'Road Maintenance -> Inspection Public Toilets','created_at' => '2020-04-25 06:58:28','updated_at' => '2020-04-25 06:58:28','deleted_at' => NULL),
            array('issue_id' => '99','lang_id' => '1','name' => 'Road Maintenance -> Gate Broken','created_at' => '2020-04-25 06:58:38','updated_at' => '2020-04-25 06:58:38','deleted_at' => NULL),
            array('issue_id' => '100','lang_id' => '1','name' => 'Water Maintenance -> Water ATM Machine Not Working','created_at' => '2020-04-25 06:58:48','updated_at' => '2020-04-25 06:58:48','deleted_at' => NULL),
            array('issue_id' => '101','lang_id' => '1','name' => 'Road Maintenance -> Road Repair','created_at' => '2020-04-25 06:58:58','updated_at' => '2020-04-25 06:58:58','deleted_at' => NULL),
            array('issue_id' => '102','lang_id' => '1','name' => 'Building Maintenance -> Broken Manhole','created_at' => '2020-04-25 06:59:11','updated_at' => '2020-04-25 06:59:31','deleted_at' => NULL),
            array('issue_id' => '103','lang_id' => '1','name' => 'Building Maintenance -> Malba Stacked','created_at' => '2020-04-25 06:59:43','updated_at' => '2020-04-25 06:59:43','deleted_at' => NULL),
            array('issue_id' => '104','lang_id' => '1','name' => 'Building Maintenance -> Sewer Problem','created_at' => '2020-04-25 06:59:53','updated_at' => '2020-04-25 06:59:53','deleted_at' => NULL),
            array('issue_id' => '105','lang_id' => '1','name' => 'Building Maintenance -> Maintenance of Building','created_at' => '2020-04-25 07:00:04','updated_at' => '2020-04-25 07:00:04','deleted_at' => NULL),
            array('issue_id' => '106','lang_id' => '1','name' => 'Building Maintenance -> Water Related Problem','created_at' => '2020-04-25 07:00:14','updated_at' => '2020-04-25 07:00:14','deleted_at' => NULL),
            array('issue_id' => '107','lang_id' => '1','name' => 'Building Maintenance -> Gate Broken','created_at' => '2020-04-25 07:00:24','updated_at' => '2020-04-25 07:00:24','deleted_at' => NULL),
            array('issue_id' => '108','lang_id' => '1','name' => 'Patient Emergency','created_at' => '2020-04-25 07:00:34','updated_at' => '2020-04-25 07:00:34','deleted_at' => NULL),
            array('issue_id' => '109','lang_id' => '1','name' => 'Health Issue','created_at' => '2020-04-25 07:00:44','updated_at' => '2020-04-25 07:00:44','deleted_at' => NULL),
            array('issue_id' => '110','lang_id' => '1','name' => 'Corona Symptoms','created_at' => '2020-04-25 07:00:58','updated_at' => '2020-04-25 07:00:58','deleted_at' => NULL),
            array('issue_id' => '111','lang_id' => '1','name' => 'Unauthorised Construction','created_at' => '2020-04-25 07:01:10','updated_at' => '2020-04-25 07:01:10','deleted_at' => NULL),
            array('issue_id' => '112','lang_id' => '1','name' => 'Unauthorised Construction -> Illegal Construction','created_at' => '2020-04-25 07:01:23','updated_at' => '2020-04-25 07:01:23','deleted_at' => NULL),
            array('issue_id' => '113','lang_id' => '1','name' => 'Unauthorised Construction  ->  Violation of Building Regulation','created_at' => '2020-04-25 07:01:38','updated_at' => '2020-04-25 07:01:38','deleted_at' => NULL),
            array('issue_id' => '114','lang_id' => '1','name' => 'Pollution due to Construction Activities','created_at' => '2020-04-25 07:01:48','updated_at' => '2020-04-25 07:01:48','deleted_at' => NULL)
        );

        if(DB::table($table_name)->get()->count() == 0) {
            DB::table($table_name)->insert($issues);
            DB::table($table_name_langs)->insert($issue_langs);
        } else {
            echo "SeedingError: `$table_name` table is not empty\n";
        }
    }
}
